### ISSUE TITLE
surface.upload() problem

### ISSUE THREAD

**Issue by ThomasKromAGL** [3ptscience/steno3dpy#1]
Hi testing Steno3d. 
First in the example you use an alias for numpy what was on defined in the example, minor but frustrating if cutting and pasting. 
When trying the surface.upload() in the example in the docs I get a crash also with .validate().
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\properties\base.py", line 217, in func_wrapper
    prop.validate(self)
  File "C:\Python34\lib\site-packages\properties\base.py", line 488, in validate
    p.validate()
  File "C:\Python34\lib\site-packages\properties\base.py", line 217, in func_wrapper
    prop.validate(self)
  File "C:\Python34\lib\site-packages\properties\base.py", line 490, in validate
    P.validate()
  File "C:\Python34\lib\site-packages\properties\base.py", line 227, in func_wrapper
    return func(self)
  File "C:\Python34\lib\site-packages\steno3d\data.py", line 48, in validate
    self._validate_file_size('array')
  File "C:\Python34\lib\site-packages\steno3d\base.py", line 44, in _validate_file_size
    if self.nbytes(name) > file_limit:
  File "C:\Python34\lib\site-packages\steno3d\data.py", line 31, in nbytes
    return self.array.nbytes
AttributeError: 'NoneType' object has no attribute 'nbytes'

**Comment by fwkoch** [comment]
@ThomasKromAGL - 
Thanks for your prompt feedback on Steno3D! The `numpy` alias will be added to the example in the next update. Regarding the validation error, when I copy and paste the example code, I don't get the error.

`In [1]:`
```python
import steno3d
steno3d.login()
proj = steno3d.Project(title='Demo Project',
                       description='My first project',
                       public=True)
import numpy as np
topo = lambda X, Y: 50*np.sinc(np.sqrt(X**2. + Y**2.)/20.)
x = np.linspace(-100, 100., num=100.)
y = np.linspace(-100., 100., num=100.)
mesh2d = steno3d.Mesh2DGrid(h1=np.diff(x), h2=np.diff(y), x0=np.r_[-100.,-100.,0.])
X, Y = np.meshgrid(x,y)
Z = topo(X, Y)
mesh2d.Z = Z.flatten(order = 'F')
surface = steno3d.Surface(project = proj, mesh = mesh2d)
surface.data = dict(location='N',
                    data=mesh2d.Z)
surface.title = 'Topo'
surface.description = 'This is a sinc function'
surface.validate()
```
`Out[1]: True`

If I modify the surface data assignment to `surface.data = dict(location='N', data=None)` I do recreate your error. I've modified the code so this error will now be `RequiredPropertyError: array` on the next update. Still an error but a bit more descriptive.

If you still are running into your validation error, can you reply with a snippet of the script you are running? Thank you!

**Comment by ThomasKromAGL** [comment]
Hi 
It seemed to work fine on my Mac. I think it could have something to do with the age of the py version on my PC??
Otherwise all seems sorted!
Thanks
Thomas

On 07 Jul 2016, at 17:37, Franklin <notifications@github.com> wrote:

@ThomasKromAGL <https://github.com/ThomasKromAGL> - 
Thanks for your prompt feedback on Steno3D! The numpy alias will be added to the example in the next update. Regarding the validation error, when I copy and paste the example code, I don't get the error.

In [1]:

import steno3d
steno3d.login()
proj = steno3d.Project(title='Demo Project',
                       description='My first project',
                       public=True)
import numpy as np
topo = lambda X, Y: 50*np.sinc(np.sqrt(X**2. + Y**2.)/20.)
x = np.linspace(-100, 100., num=100.)
y = np.linspace(-100., 100., num=100.)
mesh2d = steno3d.Mesh2DGrid(h1=np.diff(x), h2=np.diff(y), x0=np.r_[-100.,-100.,0.])
X, Y = np.meshgrid(x,y)
Z = topo(X, Y)
mesh2d.Z = Z.flatten(order = 'F')
surface = steno3d.Surface(project = proj, mesh = mesh2d)
surface.data = dict(location='N',
                    data=mesh2d.Z)
surface.title = 'Topo'
surface.description = 'This is a sinc function'
surface.validate()
Out[1]: True

If I modify the surface data assignment to surface.data = dict(location='N', data=None) I do recreate your error. I've modified the code so this error will now be RequiredPropertyError: array on the next update. Still an error but a bit more descriptive.

If you still are running into your validation error, can you reply with a snippet of the script you are running? Thank you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/3ptscience/steno3dpy/issues/1#issuecomment-231116971>, or mute the thread <https://github.com/notifications/unsubscribe/ATZRpv4j9Gt88Yu6syZZsjCbd-WSqghQks5qTR1EgaJpZM4JG9br>.



Med venlig hilsen – Best regards - С Уважением
Dr. Thomas D. Krom Ph.D.
Vice-President EMENA

ARANZ Geo Ltd.
Danmark mobile: +45 237 39685
Skype: tdkrom1
email: thomas.krom@leapfrog3d.com <mailto:thomas.krom@leapfrog3d.com>
address: Mosevej 18, Silkeborg, DK-8600
www.aranzgeo.com <http://www.aranzgeo.com/>
ARANZ Geo Limited - Owners of Leapfrog <http://www.leapfrog3d.com/>, Bloy & QG <http://www.qgconsulting.com.au/>This email is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential or copyright. You are hereby notified that any dissemination, distribution or copying of this email is strictly prohibited without the authority of the sender. If you have received this e-mail message in error or are not the intended recipient, please delete and destroy all copies and notify us immediately by return mail.  Any views expressed in this email are general in nature and not intended as a substitute for specific advice on any matter and should not be relied upon for that purpose except where the sender specifically states otherwise.

**Comment by bsmithyman** [comment]
@ThomasKromAGL: Great to hear from you, and thanks for the feedback.
@fwkoch: From the printout, it looks like Thomas is running Python 3.4 on Windows. We should probably do some more in-depth testing on 3.4, in case there is something that's not showing up on the 2.7 environment.

**Comment by fwkoch** [comment]
Thanks again. @bsmithyman - Yes, I've tested on 2.7 and 3.5 pretty extensively, but not 3.4 (and not on Windows). I'll prioritize some of those different environments.

**Comment by fwkoch** [comment]
numpy alias: https://github.com/3ptscience/steno3dpy/commit/0cbfd632d49f7290bec7a4f11d2c1259a9b510bc

array error message in DataArray (array is now a required property):
https://github.com/3ptscience/steno3dpy/commit/07b96430dce641eea31043ef623697a45cba7652

**Comment by bsmithyman** [comment]
@fwkoch: The automated tests at least run on 2.7, 3.3, 3.4 and 3.5, so anything we can put in the coverage there will get a pretty thorough treatment.
