### ISSUE TITLE
Traceback when uploading 'nothing'

### ISSUE THREAD

**Issue by ThomasMatern** [3ptscience/steno3dpy#123]
Project.upload fails with a division-by-zero error when uploading a project without any elements while using the progress_callback.
Uploading an empty project might not make much sense but I don't expect things to crash if the user decides to do something that doesn't make sense.

**Comment by rowanc1** [comment]
Is this related to #120?

**Comment by ThomasMatern** [comment]
Yes it is indeed, Sorry.
