### ISSUE TITLE
broken link in quick start docs

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dpy#16]
![quickstart steno3d 0 1 6 documentation 2016-07-13 10-41-22](https://cloud.githubusercontent.com/assets/18725251/16811688/c504548e-48e6-11e6-9ba7-4682e58ff591.png)

**Comment by bsmithyman** [comment]
Thanks @poonesh

@fwkoch, @lheagy?

**Comment by fwkoch** [comment]
Thanks, hopefully this will be fixed in the next deployment.

**Comment by fwkoch** [comment]
2 problems:
- you can no longer link to a specific notebook (at least in the same way you could before)
- you can't have a trailing slash in the URL

fixed here, and working online now:
https://github.com/3ptscience/steno3dpy/commit/4f9d3dea1a25842d314de0d47ab4308b926fbfa3
