### ISSUE TITLE
online notebooks page is hanging

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dpy#17]
![quickstart steno3d 0 1 6 documentation 2016-07-13 12-00-00](https://cloud.githubusercontent.com/assets/18725251/16814050/6aaf5d84-48f1-11e6-97e1-a3c896da9f41.png)
![steno3dpy-notebooks 2016-07-13 12-01-23](https://cloud.githubusercontent.com/assets/18725251/16814081/888b164a-48f1-11e6-890a-673d170b6a52.png)

**Comment by fwkoch** [comment]
@poonesh - mybinder.org was down this morning, I think. Can you try again and if it works, close the issue?

**Comment by poonesh** [comment]
@fwkoch - Thanks. It works now.
