### ISSUE TITLE
typo (this should say notebooks)

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dpy#18]
![quickstart steno3d 0 1 6 documentation 2016-07-13 12-38-40](https://cloud.githubusercontent.com/assets/18725251/16815414/edb3baa4-48f6-11e6-9e33-126766bb1f80.png)

**Comment by fwkoch** [comment]
Thanks, this will be fixed on the next deployment.

**Comment by fwkoch** [comment]
<img width="360" alt="screen shot 2016-07-15 at 11 07 55 am" src="https://cloud.githubusercontent.com/assets/9453731/16882477/6c3ce144-4a7c-11e6-8b63-d29f246fa1a6.png">
