### ISSUE TITLE
Surface.data documentation

### ISSUE THREAD

**Issue by dopplershift** [3ptscience/steno3dpy#23]
In the quick start example, the use of the `Surface.data` (and how it works) isn't clear from the API documentation.

**Comment by fwkoch** [comment]
@dopplershift - I've made some updates to the documentation with https://github.com/3ptscience/steno3dpy/commit/1c6b8347395446dfe5730d937f33d3fc3dc907a1:

1. The [quickstart](https://python.steno3d.com/en/latest/content/quickstart.html) now creates a DataArray more explicitly.
2. Resource API documentation pages (eg. [line](https://python.steno3d.com/en/latest/content/api/resources/line.html)) now have a bit more exposition about how to use dictionaries to bind data and options.

Thanks for the feedback! And you can re-open this issue if you still think the documentation is unclear.
