### ISSUE TITLE
`DataArray` and `Volume`

### ISSUE THREAD

**Issue by dopplershift** [3ptscience/steno3dpy#24]
It's not clear to me from the documentation, the order expected for data put into a `DataArray`, specifically to make a volume. Specifically, I have an array that is ordered (z, y, x); passing this to `DataArray` using `array.flatten(order='C')` and creating a `Volume` works fine, but frankly I'm surprised by this. I would have expected to need the array to be ordered as `x, y, z`.

**Comment by fwkoch** [comment]
@dopplershift - Thanks for the feedback on this. Currently, the ordering is based on what was done in SimPEG, developed mostly by Matlab people, and Matlab does things a bit backwards. We agree this doesn't really make sense (and quite quickly becomes a point of frustration...).

The way it should work as you suggest is `data.shape == (x-dim, y-dim, z-dim)` then using `data.flatten()` (with numpy's default, order 'C') produces the correctly-sorted array. Hopefully this will be updated in the next couple days (both in the code and in the documentation).

**Comment by fwkoch** [comment]
@dopplershift - Our fix for this has been deployed with version 0.2.0. The default is now C-style, row-major ordering (where flattening an array of shape (x, y, z) produces the correct results). The old Fortran-style, column-major ordering is still available, you just need to specify `order='f'` when constructing a `DataArray`.

I have also updated the documentation for [Data](https://python.steno3d.com/en/latest/content/api/resources/data.html) and [Volume](https://python.steno3d.com/en/latest/content/api/resources/volume.html) accordingly.

I hope this clears things up a bit and makes your workflow more straightforward. Thank you again for the feedback, and if you run into any trouble please re-open this issue or make a new one!
