### ISSUE TITLE
how do I install module vmath?

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3dpy#68]
I am going through the example jupyter notebooks and in the notebook Steno3D Resources

the following import fails 
from properties.vmath import Vector

I am running Anaconda on Windows 7 pro. I have steno3d installed in a seperate conda environment. I suspect the problem is I just need to link vmath to the enviroment but I can't find what name it might be called by. There is an llvmmath is this it?

**Comment by rowanc1** [comment]
We recently moved from `properties` to `traitlets` it is possible that the (or your) notebooks are out of date with that. As such, the vector should not be necessary, you should be able to make a 3 length python list or numpy array.

**Comment by fwkoch** [comment]
@hal98x -

Thanks for pointing out this oversight in our migration from `properties` to `traitlets`. The notebooks have now been updated to no longer require `from properties.vmath import Vector` with this commit https://github.com/3ptscience/steno3dpy-notebooks/commit/115e27caa7b609f89cb9316ebfa51f60daab77cd. Hopefully after you pull the updated notebooks, everything will run smoothly.

Let us know if run into any other problems or questions. As a side note: hopefully in the next couple weeks we will roll out some new, shorter notebooks that may be easier to digest than the current, enormous Steno3D Resources notebook. If that interests you, keep an eye out.

**Comment by fwkoch** [comment]
P.S. The old version of the notebook (with `from properties.vmath import Vector`) should also work if you `pip install properties` at the command line. However, this module is no longer a requirement for `steno3d`, so it's probably better to update the notebooks rather than clutter up your environment more.

**Comment by hal98x** [comment]
Thanks @rowanc1 @fwkoch for the quick response and resolution. The Steno Resources notebook is a bit long and could be broken up but its fine for now. I am working through it to see what I will need in terms of pre-processing functionality to input data.
